# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.nameInputLayout = QtWidgets.QHBoxLayout()
        self.nameInputLayout.setSpacing(11)
        self.nameInputLayout.setObjectName("nameInputLayout")
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameEdit.setText("")
        self.usernameEdit.setObjectName("usernameEdit")
        self.nameInputLayout.addWidget(self.usernameEdit)
        self.addPlayerButton = QtWidgets.QPushButton(self.centralwidget)
        self.addPlayerButton.setEnabled(False)
        self.addPlayerButton.setObjectName("addPlayerButton")
        self.nameInputLayout.addWidget(self.addPlayerButton)
        self.verticalLayout_4.addLayout(self.nameInputLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.team1GrpBx = QtWidgets.QGroupBox(self.centralwidget)
        self.team1GrpBx.setObjectName("team1GrpBx")
        self.gridLayout = QtWidgets.QGridLayout(self.team1GrpBx)
        self.gridLayout.setObjectName("gridLayout")
        self.team1List = QtWidgets.QListWidget(self.team1GrpBx)
        self.team1List.setMinimumSize(QtCore.QSize(475, 0))
        self.team1List.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.team1List.setObjectName("team1List")
        self.gridLayout.addWidget(self.team1List, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.team1GrpBx)
        self.removePlayerTeam1Button = QtWidgets.QPushButton(self.centralwidget)
        self.removePlayerTeam1Button.setObjectName("removePlayerTeam1Button")
        self.verticalLayout_3.addWidget(self.removePlayerTeam1Button)
        self.team2GrpBx = QtWidgets.QGroupBox(self.centralwidget)
        self.team2GrpBx.setFlat(False)
        self.team2GrpBx.setCheckable(False)
        self.team2GrpBx.setObjectName("team2GrpBx")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.team2GrpBx)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.team2List = QtWidgets.QListWidget(self.team2GrpBx)
        self.team2List.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.team2List.setObjectName("team2List")
        self.gridLayout_2.addWidget(self.team2List, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.team2GrpBx)
        self.removePlayerTeam2Button = QtWidgets.QPushButton(self.centralwidget)
        self.removePlayerTeam2Button.setObjectName("removePlayerTeam2Button")
        self.verticalLayout_3.addWidget(self.removePlayerTeam2Button)
        self.teamAddPointsLayout = QtWidgets.QHBoxLayout()
        self.teamAddPointsLayout.setObjectName("teamAddPointsLayout")
        self.teamRemoveButton = QtWidgets.QPushButton(self.centralwidget)
        self.teamRemoveButton.setObjectName("teamRemoveButton")
        self.teamAddPointsLayout.addWidget(self.teamRemoveButton)
        spacerItem = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.teamAddPointsLayout.addItem(spacerItem)
        self.teamAddButton = QtWidgets.QPushButton(self.centralwidget)
        self.teamAddButton.setObjectName("teamAddButton")
        self.teamAddPointsLayout.addWidget(self.teamAddButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.teamAddPointsLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.teamAddPointsLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.playerPoolList = QtWidgets.QListWidget(self.centralwidget)
        self.playerPoolList.setMinimumSize(QtCore.QSize(411, 0))
        self.playerPoolList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.playerPoolList.setObjectName("playerPoolList")
        self.verticalLayout.addWidget(self.playerPoolList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.putTeam1Button = QtWidgets.QPushButton(self.centralwidget)
        self.putTeam1Button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.putTeam1Button.setObjectName("putTeam1Button")
        self.horizontalLayout_2.addWidget(self.putTeam1Button)
        self.putTeam2Button = QtWidgets.QPushButton(self.centralwidget)
        self.putTeam2Button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.putTeam2Button.setObjectName("putTeam2Button")
        self.horizontalLayout_2.addWidget(self.putTeam2Button)
        self.plusPointButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusPointButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.plusPointButton.setObjectName("plusPointButton")
        self.horizontalLayout_2.addWidget(self.plusPointButton)
        self.minusPointButton = QtWidgets.QPushButton(self.centralwidget)
        self.minusPointButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.minusPointButton.setObjectName("minusPointButton")
        self.horizontalLayout_2.addWidget(self.minusPointButton)
        self.removePlayerButton = QtWidgets.QPushButton(self.centralwidget)
        self.removePlayerButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.removePlayerButton.setObjectName("removePlayerButton")
        self.horizontalLayout_2.addWidget(self.removePlayerButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1165, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "League Night"))
        self.usernameEdit.setPlaceholderText(_translate("MainWindow", "Enter Summoner Name"))
        self.addPlayerButton.setText(_translate("MainWindow", "Add To Team"))
        self.team1GrpBx.setTitle(_translate("MainWindow", "Team 1"))
        self.removePlayerTeam1Button.setText(_translate("MainWindow", "Remove Player(s)"))
        self.team2GrpBx.setTitle(_translate("MainWindow", "Team 2"))
        self.removePlayerTeam2Button.setText(_translate("MainWindow", "Remove Player(s)"))
        self.teamRemoveButton.setText(_translate("MainWindow", "Remove Points"))
        self.teamAddButton.setText(_translate("MainWindow", "Add Points"))
        self.label.setText(_translate("MainWindow", "Player Pool"))
        self.putTeam1Button.setText(_translate("MainWindow", "Team 1"))
        self.putTeam2Button.setText(_translate("MainWindow", "Team 2"))
        self.plusPointButton.setText(_translate("MainWindow", "Give Point"))
        self.minusPointButton.setText(_translate("MainWindow", "Lose Point"))
        self.removePlayerButton.setText(_translate("MainWindow", "Remove"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

